### ISSUE TITLE
rgb_to_hex.py bugs

### ISSUE THREAD

**Issue by chloedhoff** [chloedhoff/CS-120-Advanced-Programming-CLT#5]
Description : there is an error with variable name r, it is not consistent and refrenced as ra. also the max number of 255 is inconsistent, under variable ra it is 265. there is also no colon after the declaration of the method

Steps to Reproduce

to reproduce this bug you would change the variable name r to ra where first declared. also you would change the max amount from 255 to 265 within the parentheses. you would remove the ":" after the def of the method

Expected Behavior: I would expect the code not to run because there will now be undeclared variables being used later in the code. as well as the code not recognizing it as a method because there is no :.The colors will come out not expected because of the changed 255 number.

Actual Behavior The program did not run due to the missing colon after the def.

Screenshots If applicable, add screenshots to help explain the issue/bug.

Additional Information

Operating System: OS
Browser: IDLE
Version: 3.11.2
Possible Solution: add a colon after the declaration of method before the indented lines. change 265 back to 255, and change ra to r.

Priority How critical is this issue/bug:
high, unable to run until fixed

Reproducibility How often can this issue/bug be reproduced: this can be easily reproduced. it is an issue from the coder.

Impact What is the impact of this issue/bug: high impact, the code is unable to run until fixed

**Comment by lilyycarr** [comment]
These fixes are correct:
Added a colon after the declaration of method before the indented lines. 
Changed 265 to 255.
Change ra to r.
